### ISSUE TITLE
Move pop-up when Excel is moved

### ISSUE THREAD

**Issue by Ron-Ldn** [Excel-DNA/IntelliSense#7] opened 2015-04-07 13:46 UTC
When Excel is moved or reduced, the pop-up stays where it is.

**Comment by govert** [comment] 2015-04-07 23:15
I think related: the argument help pop-up should stay in front of the Excel window. At the moment it can get behind Excel (when Excel is resized) and then appears behind Excel for future help sessions too.

**Comment by Ron-Ldn** [comment] 2015-04-16 10:07
I can't manage to make it get behind Excel. It is only when the Excel window is resized or are there more steps to follow ?
I have tried with Excel 2010 and Excel 2013, both with Windows 7, and no issue.

**Comment by Ron-Ldn** [comment] 2015-04-16 10:10
The pop-ups are now following the Excel window when it is moved. The watchers are actually subscribing to the BoundingRectangle property changed event.
Performance does not seem to be impacted.

**Comment by govert** [comment] 2015-04-16 11:56
I can't reproduce where it goes behind the window now. Will look out for it still.
We also need to test with Excel 2013 with multiple windows (in the same session). If you're editing a formula in one window, then switch to another one, and things go horribly wrong (esp. when switching back).

**Comment by andrewkittredge** [comment] 2015-04-16 14:14
I am testing on Excel 2013.  I can verify the pop-ups are tracking when the window is moved.

I tested with two windows open.  Both windows worked for a couple of minutes then the below error was thrown and things went downhill.  Can I provide more details?

line 567 of Watchers.cs
NonComVisibleBaseClass was detected
Message: A QueryInterface call was made requesting the class interface of COM visible managed class 'MS.Internal.AutomationProxies.ListViewItem'. However since this class derives from non COM visible class 'MS.Internal.AutomationProxies.ProxyFragment', the QueryInterface call will fail. This is done to prevent the non COM visible base class from being constrained by the COM versioning rules.

**Comment by Ron-Ldn** [comment] 2016-06-23 13:09
@govert: I see that the fix I implemented a while ago is commented now and the issue came back. Did you find a problem with it? Or did you forget to uncomment it after some refactoring?

**Comment by govert** [comment] 2016-08-12 20:43
I've implemented this feature again.

**Comment by govert** [comment] 2016-08-14 14:13
Should be fixed in release https://github.com/Excel-DNA/IntelliSense/releases/tag/v0.1.6-beta6

**Closed by govert** 2016-08-14 14:13 UTC
